FROM marcskovmadsen/awesome-streamlit_base:latest

WORKDIR /app
ADD . ./

# Default port for Azure Web App for containers is 80
# Please note that port and serverPort in the config.toml file
# should correspond to the exposed port
EXPOSE 80

RUN mkdir ~/.streamlit
RUN cp .streamlit/config.prod.toml ~/.streamlit/config.toml
RUN cp .streamlit/credentials.prod.toml ~/.streamlit/credentials.toml
RUN cp app/config.prod.py app/config.py

WORKDIR /app

ENTRYPOINT [ "streamlit", "run", "app/main.py" ]