FROM marcskovmadsen/awesome-streamlit_base:latest

EXPOSE 8000

WORKDIR /app
ADD . ./

RUN mkdir /tmp/build/
# Add context to /tmp/build/
COPY . /tmp/build

# this last command outputs the list of files added to the build context:
RUN find /tmp/build/

RUN mkdir ~/.streamlit
RUN cp .streamlit/config.prod.toml ~/.streamlit/config.toml
RUN cp .streamlit/credentials.prod.toml ~/.streamlit/credentials.toml

WORKDIR /app

ENTRYPOINT [ "streamlit", "run", "src/app.py" ]